### ISSUE TITLE
[Bug] Phantom Walls being created

### ISSUE THREAD

**Issue by badgkat** [Saibot393/perceptive#56] opened 2023-12-14 04:28 UTC
This has happened several times, and I believe I have narrowed it down to perspective. It may be associated with the walls created during lock peeking.

My players will open a door and they have no vision through it. 
<img width="243" alt="Screenshot 2023-12-13 212324" src="https://github.com/Saibot393/perceptive/assets/109937927/e5ced111-4e4b-4845-b789-9d667761aaa1">
I look in the walls tab, and nothing is amiss
<img width="195" alt="Screenshot 2023-12-13 212232" src="https://github.com/Saibot393/perceptive/assets/109937927/640bc3ec-5a4e-41b5-92c3-7f84c5878779">
I disable perceptive, and I can now see there are a number (sometimes dozens) of walls in that doorway.
 
<img width="293" alt="Screenshot 2023-12-13 212118" src="https://github.com/Saibot393/perceptive/assets/109937927/94552d90-b5b3-4320-a5f8-9b00a5a41a2b">

**Comment by Saibot393** [comment] 2023-12-14 06:09
I will look into it. Are these doors set as peekable or moving?

**Comment by Saibot393** [comment] 2023-12-14 06:45
Also, what other modules are you using?

**Comment by Saibot393** [comment] 2023-12-14 13:30
I did a bit of testing but can not replicate the creation of these walls. I have a rough idea what could cause that. It likely is some kind of compatibility problem with another module.

**Comment by badgkat** [comment] 2023-12-15 00:14
> Also, what other modules are you using?

Too many to count. Though most are content modules and shouldn't affect the canvas, key possibilities for conflicts:

PF2e Perception
Monk's Improved Walls
Wall Hight
Levels 


Full list (not all of these were enabled the first time it happened):
### Active Modules
Advanced Drawing Tools v2.1.0 [Bugs URL](https://github.com/dev7355608/advanced-drawing-tools/issues)
Arms Reach v2.3.6 [Bugs URL](https://github.com/p4535992/foundryvtt-arms-reach/issues)
Auto-Rotate vv1.3.17 [Bugs URL](https://github.com/Varriount/fvtt-autorotate/issues)
Baileywiki Nuts and Bolts v0.2.5
Battlezoo Ancestries: Dragons for Pathfinder 2e by Roll for Combat v1.4.2
Battlezoo Ancestries: Dungeons for Pathfinder 2e by Roll for Combat v1.2
Battlezoo Ancestries: Year of Monsters for Pathfinder 2e by Roll for Combat v12.01
Battlezoo Bestiary for Pathfinder 2e by Roll For Combat v2.5
Battlezoo Bestiary: Strange and Unusual for Pathfinder 2e by Roll For Combat v1.0.1
Battlezoo Jewel of the Indigo Isles for Pathfinder 2e by Roll for Combat v3.1.1
Battlezoo — World of Battlezoo: Indigo Isles for Pathfinder 2e v1.1.2
Better Roofs v1.9.2
Break Time v11.03 [Bugs URL](https://github.com/ironmonk88/breaktime/issues)
Carousel Combat Tracker v2.6.1
DF Settings Clarity v3.3.0 [Bugs URL](https://github.com/flamewave000/dragonflagon-fvtt/issues/new/choose)
Dice So Nice! v4.6.8 [Bugs URL](https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/issues)
Dice Stats v1.15.0
Dice Tray v2.1.5
Drag Ruler v1.13.8 [Bugs URL](https://github.com/manuelVo/foundryvtt-drag-ruler/issues)
PF2e Drag Ruler Integration v3.0.5
Footsteps of Otari v2.0.1
Force Client Controls v1.0.5 [Bugs URL](https://gitlab.com/kimitsu_desu/force-client-controls/-/issues)
Forien's Quest Log v0.7.12 [Bugs URL](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/issues)
FXMaster v4.0.2 [Bugs URL](https://github.com/ghost-fvtt/fxmaster/issues)
Jack Kerouac's Animated Spell Effects: Cartoon v0.4.5
JB2A - Jules and Ben's Animated Assets - Free Content v0.6.3
PF2E Troubles in Otari Enhanced Beach Camp by Wise v1.2.3
JB2A - Patreon Complete Collection v0.6.2
Kris's Compendium of Trade Goods - PF2e edition v1.1.3
Chat Commander v2.0.1 [Bugs URL](https://gitlab.com/woodentavern/foundryvtt-chat-command-lib/-/issues)
lib - Color Settings v3.0.1
Library: Scene Packer v2.7.8 [Bugs URL](https://github.com/League-of-Foundry-Developers/scene-packer/issues)
libWrapper v1.12.13.0 [Bugs URL](https://github.com/ruipin/fvtt-lib-wrapper/issues)
Settings Extender v1.2.2
socketlib v1.0.13 [Bugs URL](https://github.com/manuelVo/foundryvtt-socketlib/issues)
Lock & Key v2.3.0 [Bugs URL](https://github.com/Saibot393/LocknKey/issues)
Baileywiki Maps Premium v0.5.5
Baileywiki Maps Towns v0.5.8
Mass Edit v1.51.0
Michael Ghelfi Studios Audio Pack v1.4
Module Management+ v2.2.3 [Bugs URL](https://github.com/mouse0270/module-credits/issues)
Monk's Active Tile Triggers v11.17 [Bugs URL](https://github.com/ironmonk88/monks-active-tiles/issues)
Monk's Bloodsplats v11.11 [Bugs URL](https://github.com/ironmonk88/monks-bloodsplats/issues)
Monk's Combat Details v11.09 [Bugs URL](https://github.com/ironmonk88/monks-combat-details/issues)
Monk's Combat Marker v11.03 [Bugs URL](https://github.com/ironmonk88/monks-combat-marker/issues)
Monk's Enhanced Journal v11.07 [Bugs URL](https://github.com/ironmonk88/monks-enhanced-journal/issues)
Monk's Hotbar Expansion v10.1 [Bugs URL](https://github.com/ironmonk88/hotbar-expansion/issues)
Monk's Little Details v11.05 [Bugs URL](https://github.com/ironmonk88/monks-little-details/issues)
Monk's PF2e Encounter Aftermath v11.05 [Bugs URL](https://github.com/ironmonk88/monks-pf2e-encounter-aftermath/issues)
Monk's Player Settings v11.04 [Bugs URL](https://github.com/ironmonk88/monks-player-settings/issues)
Monk's Scene Navigation v11.02 [Bugs URL](https://github.com/ironmonk88/monks-scene-navigation/issues)
Monk's Sound Enhancements v11.05 [Bugs URL](https://github.com/ironmonk88/monks-sound-enhancements/issues)
Monk's TokenBar v11.08 [Bugs URL](https://github.com/ironmonk88/monks-tokenbar/issues)
Monk's Wall Enhancement v11.02 [Bugs URL](https://github.com/ironmonk88/monks-wall-enhancement/issues)
Moulinette Core v11.6.4
Moulinette Game Icons (module) v11.1.1
Moulinette Scenes (module) v11.1.3
Moulinette Sounds & SoundPad (module) v11.8.2
Moulinette Tiles (module) v11.1.0
Moulinette Image Search (module) v11.0.1
Multiface Tiles v1.0.11
Party Resources v1.6.0
Pathfinder 2e: Abomination Vaults v3.1.0
Pathfinder Beginner Box v3.0.0
Pathfinder: Harrow v1.1.1
Pathfinder: Kingmaker v2.0.0
Pathfinder Token Pack: Bestiaries v1.0.6
Patrol v1.3.4
Perceptive v3.1.7
PF2e Action Support Engine v0.0.96
PF2e Action Support Engine Handlers v0.0.33
PF2e Action Support Engine Macros v0.0.25
PF2e Action Support Engine Measure Helper v0.0.18
PF2e a shopping experience v3.0.0
PF2e Companion Compendia v6.0
PF2e Convenient Consumables v1.0.1 [Bugs URL](https://github.com/JDCalvert/pf2e-convenient-consumables/issues)
PF2e Dailies v2.16.0 [Bugs URL](https://github.com/reonZ/pf2e-dailies/issues)
PF2e Dorako UX v1.2.0 [Bugs URL](https://github.com/Dorako/pf2e-dorako-ux/issues)
PF2e Dying v0.0.12
PF2E Exploration Effects v3.0.0
pf2E Extempore Effects v1.8.2 [Bugs URL](https://github.com/shemetz/pf2e-extempore-effects/issues)
PF2E Fatigue v1.3.7
PF2e Flip Token v0.0.3 [Bugs URL](https://github.com/reyzor1991/foundry-vtt-pf2e-flip-token/issues)
PF2e Hands Management (Reminder) v0.0.14 [Bugs URL](https://github.com/reyzor1991/foundry-vtt-pf2e-notification/issues)
PF2e Interactive Token Tooltip v1.57.0 [Bugs URL](https://github.com/reonZ/pf2e-token-hud/issues)
PF2e Keybind Menagerie v5.3.2
PF2e Mercenary Marketplace Volume 1 v3.0.5
Pf2E Modifiers Matter v1.8.8 [Bugs URL](https://github.com/shemetz/pf2e-modifiers-matter/issues)
PF2E Monster Maker v1.2.3
PF2e Party Sheet Helper v0.0.49 [Bugs URL](https://github.com/reyzor1991/pf2e-party-sheet-helper/issues)
PF2e Perception v0.33.0 [Bugs URL](https://github.com/reonZ/pf2e-perception/issues)
PF2e Ranged Combat v4.0.8 [Bugs URL](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/issues)
PF2e Reaction Checker v0.2.53 [Bugs URL](https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/issues)
PF2e Relics v0.9.8
pF2e See Simple Scale Statistics v1.4.1 [Bugs URL](https://github.com/shemetz/pf2e-see-simple-scale-statistics/issues)
PF2e Toolbelt v1.26.0 [Bugs URL](https://github.com/reonZ/pf2e-toolbelt/issues)
PF2e Troops Helper v0.0.5
PF2e Tweaks by Ustin v0.7.2
PF2e Use all module tokens v1.4
PF2e Weapon Trait Options v0.0.5
PF2e Workbench v5.37.12 [Bugs URL](https://github.com/xdy/xdy-pf2e-workbench/issues)
Pin Cushion v1.9.11 [Bugs URL](https://github.com/p4535992/foundryvtt-pin-cushion/issues)
Polyglot v2.3.18
PopOut! v2.14 [Bugs URL](https://github.com/League-of-Foundry-Developers/fvtt-module-popout/issues)
Quick Insert - Search Widget v2.8.3 [Bugs URL](https://gitlab.com/fvtt-modules-lab/quick-insert/-/issues)
Rideable v2.17.0 [Bugs URL](https://github.com/Saibot393/Rideable/issues)
routinglib v1.1.0 [Bugs URL](https://github.com/manuelVo/foundryvtt-routinglib/issues)
Select tool everywhere v1.4.1
Sequencer v3.1.4 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-Sequencer/issues)
Automated Animations v4.2.69
PF2e Animation Macros v2.17.2
PF2e Summons Helper v0.0.5
Simple Calendar v2.4.3 [Bugs URL](https://github.com/vigoren/foundryvtt-simple-calendar/issues)
Smart Target v1.0.1 [Bugs URL](https://github.com/theripper93/Smart-Target/issues)
Splatter v3.4.2
Sync Token Names v1.0.5
Tactical Grid v1.18.6
Tagger v1.4.5 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-Tagger/issues)
TheRipper93's Module Hub v2.0
Tile Scroll v2.2
Token Attacher vv4.5.15
Baileywiki Cabal Dungeon v0.2.3
Baileywiki Modular City - District 01 v0.2.4
Baileywiki Modular City - District 02: Docks v0.2.0
Baileywiki Modular City - District 03: Temples v0.2.0
Baileywiki Modular City - District 04: Ruins and Slums v0.2.1
Baileywiki Modular City - District 05: Affluent v0.2.1
Token Lean: Peek Around Corners v2.1.0 [Bugs URL](https://github.com/WesBelmont/token-lean/issues)
Token Magic FX v0.6.5.0
PF2e TokenMagic Integration v0.2.0
Token Magic FX - Automatic Wounds v1.1.6 [Bugs URL](https://github.com/shemetz/tokenmagic-automatic-wounds/issues)
Token Mold v2.20.3 [Bugs URL](https://github.com/Moerill/token-mold/issues)
Minimal UI v1.6.8
PF2e Dorako UI v3.3.2 [Bugs URL](https://github.com/Dorako/pf2e-dorako-ui/issues)
Vauxs' Chat Enhancements v0.4.0 [Bugs URL](https://github.com/mrvauxs/vauxs-chat-enhancements/issues)
Wall Height v5.1.3
Levels v4.2.9
Warp Gate v1.19.2
Foundry Summons v1.7.0 [Bugs URL](https://github.com/mrvauxs/foundry-summons/issues)

**Comment by badgkat** [comment] 2023-12-15 00:16
> I will look into it. Are these doors set as peekable or moving?

Peekable

**Comment by Saibot393** [comment] 2023-12-15 09:18
I have released v3.1.8, i am not sure if completely resolves the issue, but it should make the bug atleast less likely to appear

**Comment by Dyrnwyrm** [comment] 2023-12-23 03:43
Got the same issue when i resized a map from 150 grid to 100, also for some reason when i pick an option from opening doors like sliding or swinging my players got this weird issue of the door opening and closing

**Comment by Saibot393** [comment] 2023-12-23 09:48
Are you using Monk's Wall Enhancement for resizing? Also, did this happen with the newest version?

**Comment by Dyrnwyrm** [comment] 2023-12-23 18:29
Yep Monk´s Wall enhancement, the issue is that even when i deleted all the walls the phantom walls persist, i ended up deleting all the scenes and making the walls manually and my other issue seems like is related to choosing swinging doors or the other option (not foundry default)

**Comment by Saibot393** [comment] 2023-12-23 21:27
I tested a bit and can' replicate the behaviour. I will continue investigating after christmas. Just in case it is some kind of strange compatibility issue, which modules are you using?

**Comment by Dyrnwyrm** [comment] 2023-12-23 22:09
sure let me add the list and the door issue is for players only for some weird reason i 100% sure is something related to using other type of doors that are not "core behavior" 

### Active Modules
Action Pack v11.2 [Bugs URL](https://github.com/teroparvinen/foundry-action-pack/issues)
Active Auras v0.9.2 [Bugs URL](https://github.com/kandashi/Active-Auras/issues)
Active Token Effects v0.7.0 [Bugs URL](https://github.com/kandashi/Active-Token-Lighting/issues)
Advanced Macros v2.0.5 [Bugs URL](https://github.com/League-of-Foundry-Developers/fvtt-advanced-macros/issues)
Anonymous v1.4.4 [Bugs URL](https://github.com/reonZ/anonymous/issues)
Arms Reach v2.3.6 [Bugs URL](https://github.com/p4535992/foundryvtt-arms-reach/issues)
Build-a-Bonus v11.6.2
Carousel Combat Tracker v2.6.1
Chat Portrait v0.9.4 [Bugs URL](https://github.com/p4535992/foundryvtt-chat-portrait/issues)
Cleaner sheet title bar v1.5.1
Combat Booster: Turn Marker, Recent Actions and more v3.6.2
DDB-Importer: A D&D Beyond Integrator v3.6.0
DFreds Convenient Effects v6.0.0 [Bugs URL](https://github.com/DFreds/dfreds-convenient-effects/issues)
DFreds Droppables v3.0.1 [Bugs URL](https://github.com/DFreds/dfreds-droppables/issues)
DFreds Effects Panel v3.1.0 [Bugs URL](https://github.com/DFreds/dfreds-effects-panel/issues)
Dice So Nice! v4.6.9 [Bugs URL](https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/issues)
DND5E Scriplets - 5E QOL bits and pieces v0.23
Dynamic effects using Active Effects (DAE) v11.1.7 [Bugs URL](https://gitlab.com/tposney/dae/-/issues)
Midi QOL v11.3.10 [Bugs URL](https://gitlab.com/tposney/midi-qol/-/issues)
Chris's Premades v0.9.14
Midi SRD v11.0.0 [Bugs URL](https://github.com/thatlonelybugbear/midi-srd/issues)
Effect Macro v11.0.3
Foundry Redirect: Better invitation links v2.0.4
Grid Scaler v1.4.4
Health Estimate v31.7.9 [Bugs URL](https://github.com/mclemente/healthEstimate/issues)
Illandril's Inventory Sorter (5e) v2.3.0 [Bugs URL](https://github.com/illandril/FoundryVTT-inventory-sorter/issues)
Item Collection\Item Container for Dnd5e v11.0.4
Item Piles v2.8.12 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues)
JB2A - Patreon Complete Collection v0.6.3
Kris's Compendium of Trade Goods v0.13
lib - Color Settings v3.0.1
🏷️ Item Tags (Library) v1.1.0 [Bugs URL](https://github.com/ZotyDev/FoundryVTT-ItemTags/issues)
libWrapper v1.12.13.0 [Bugs URL](https://github.com/ruipin/fvtt-lib-wrapper/issues)
socketlib v1.0.13 [Bugs URL](https://github.com/manuelVo/foundryvtt-socketlib/issues)
Limits v1.1.0 [Bugs URL](https://github.com/dev7355608/limits/issues)
Magic Items 2 v1.3.3 [Bugs URL](https://github.com/PwQt/magic-items-2/issues)
Universal Battlemap Importer v3.0.0
Mass Edit v1.54.0
Material Components v11.1.3 [Bugs URL](https://github.com/M0nk3yy/MC5e/issues)
Module Management+ v2.2.3 [Bugs URL](https://github.com/mouse0270/module-credits/issues)
Monk's Bloodsplats v11.11 [Bugs URL](https://github.com/ironmonk88/monks-bloodsplats/issues)
Monk's Combat Details v11.09 [Bugs URL](https://github.com/ironmonk88/monks-combat-details/issues)
Monk's Combat Marker v11.03 [Bugs URL](https://github.com/ironmonk88/monks-combat-marker/issues)
Monk's Enhanced Journal v11.08 [Bugs URL](https://github.com/ironmonk88/monks-enhanced-journal/issues)
Monk's Player Settings v11.04 [Bugs URL](https://github.com/ironmonk88/monks-player-settings/issues)
Monk's TokenBar v11.09 [Bugs URL](https://github.com/ironmonk88/monks-tokenbar/issues)
Monk's Wall Enhancement v11.02 [Bugs URL](https://github.com/ironmonk88/monks-wall-enhancement/issues)
Perceptive v3.1.8
Polyglot v2.3.18
Rarity Colors v0.3.7 [Bugs URL](https://github.com/p4535992/foundryvtt-rarity-colors/issues)
Rest Recovery for 5E v1.5.2
Reverse Initiative Order v1.2.1 [Bugs URL](https://github.com/sun-dragon-cult/fvtt-module-reverseinitiativeorder/issues)
Revised Weapons & Equipment v11.0.0
Rideable v2.17.2 [Bugs URL](https://github.com/Saibot393/Rideable/issues)
routinglib v1.1.0 [Bugs URL](https://github.com/manuelVo/foundryvtt-routinglib/issues)
Sequencer v3.1.4 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-Sequencer/issues)
Automated Animations v4.2.69
D&D5e Animations v1.6.0
✨ Automated Objects, Interactions and Effects 🔥 v1.1.5 [Bugs URL](https://github.com/ZotyDev/objects-interactions-fx/issues)
Universal Animations v0.1.3
Show Token Art v1.0.3
Shuggaloaf's Simple NPC Generator vv4.0.11
Simple Calendar v2.4.3 [Bugs URL](https://github.com/vigoren/foundryvtt-simple-calendar/issues)
Simple Weather v1.8.0 [Bugs URL](https://github.com/dovrosenberg/foundry-simple-weather/issues)
SmallTime v1.19.1 [Bugs URL](https://github.com/unsoluble/smalltime/issues)
Smart Target v1.0.1 [Bugs URL](https://github.com/theripper93/Smart-Target/issues)
Stairways (Teleporter) v0.10.2 [Bugs URL](https://gitlab.com/SWW13/foundryvtt-stairways/issues)
Stealthy v3.13.2 [Bugs URL](https://github.com/Eligarf/stealthy/issues)
Tagger v1.4.5 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-Tagger/issues)
Template Macro v11.0.1
Tidy5e Sheet v0.10.0 [Bugs URL](https://github.com/sdenec/tidy5e-sheet/issues)
Times Up v11.1.1 [Bugs URL](https://gitlab.com/tposney/times-up/-/issues)
Token Attacher vv4.5.15
Token Auras v2.7
Token Ease v1.2.1
Token Magic FX v0.6.5.0
Token Magic FX - Automatic Wounds v1.1.7 [Bugs URL](https://github.com/shemetz/tokenmagic-automatic-wounds/issues)
Token Mold v2.20.3 [Bugs URL](https://github.com/Moerill/token-mold/issues)
Token Variant Art v4.62.5 [Bugs URL](https://github.com/Aedif/TokenVariants/issues)
Token Warp v11.0.1.1 [Bugs URL](https://github.com/thatlonelybugbear/token-warp/issues)
Variant Encumbrance+Midi vv0.13.5 [Bugs URL](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/issues)
Vision 5e v1.12.0 [Bugs URL](https://github.com/dev7355608/vision-5e/issues)
Walled Templates v0.6.10
Warp Gate v1.19.2
Arbron’s Summoning v1.1.4 [Bugs URL](https://github.com/arbron/fvtt-summoner/issues)

**Comment by Saibot393** [comment] 2023-12-23 22:41
You mentioned that this bug only appears for players, which makes it sound like it might be lag related. I have released a small fix with v3.1.9 that might fix the bug, should it indeed be lag related.

**Comment by pavelradvan** [comment] 2023-12-24 14:51
Hi. I have same problem. It is appearing for GM and for Players also. When I disable "Can be lock peeked" it is OK.

**Comment by Saibot393** [comment] 2023-12-29 10:34
I have released v3.1.10 which should prevent this from happening by preloading all walls necessary

**Comment by pavelradvan** [comment] 2023-12-29 15:29
Yes, that phantom automatic walls are appearing. I have dedicated computer with Windows 11 Pro for Foundry. Foundry is latest v11 and running in Node not as Windows app. I am connecting to it by local LAN.
I also tried to restart server several times and it is same.
I also have VPS from my server hosting provider, but it is now disabled, because I am preparing all on local server and then just transfer "data" folder to VPS.
That visible secret doors on another levels seems to be only for GM(me) not for players, but it is quite annoying to have all secret doors duplicated on all levels...

**Comment by Saibot393** [comment] 2023-12-29 18:13
Could you send me the world file of this empty world you had the phantom walls appear in?

**Comment by pavelradvan** [comment] 2023-12-29 21:33
OK. I prepare walls and doors with active setting from your module.
Which file exactly you would like to have? How I could send it with some privacy ?

**Comment by Saibot393** [comment] 2023-12-29 22:00
i need the world file from the worlds directory, if you want you can send to me via discord DM at saibot5279

**Comment by pavelradvan** [comment] 2023-12-29 23:03
I sent all on Discord with DM to you

**Comment by pavelradvan** [comment] 2023-12-29 23:04
I have od Discord name wyrm9426

**Comment by Saibot393** [comment] 2024-01-03 22:55
The issues described here should be solved, i will close this issue soon unless i hear otherwise

**Closed** 2024-02-14 22:06 UTC
Labels: bug
