### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by XXDarrienX** [Saibot393/perceptive#24] opened 2023-09-28 15:24 UTC
Not sure which update it was but when you click on tokens now, it bogs down to the point you can't even move the map, the token or anything., I have any of the performance effecting settings turned off. The moment I turn the module off the problem goes away.

**Comment by Saibot393** [comment] 2023-09-28 15:27
Do any errors show up in the console? Also, could you send me a screenshot of you spotting settings?

**Comment by Saibot393** [comment] 2023-09-28 15:40
Thank you. Could you send me a screenshot/copy paste of the errors? If thats not possible, could you send me a list of the modules you use?

**Comment by XXDarrienX** [comment] 2023-09-28 15:45
Well I am testing today and it does not seem to happen right now, and its only really able to test next time I run my session but here is my active module list

Active Modules:
----------
5e - Custom Abilities & Skills v;
5e-Sheet Resources Plus v;
5e Statblock Importer v;
About Time v;
Active-Auras v;
Active Token Effects v;
Add a Resource v;
Advanced Macros v;
Advantage Reminder for dnd5e v;
Always HP v;
Angela Maps - Free Map Pack v;
Argon - Combat HUD v;
Automated Animations v;
Automated Conditions 5e v;
Auto-Rotate v;
Backpack Manager v;
Beaver's Crafting Module v;
Beaver's System Adaption dnd5e v;
Beaver's System Adaption pf2e v;
Beaver's System Interface v;
Better NPC Sheet 5e v;
Better Roofs v;
Build-a-Bonus v;
Caeora's Maps, Tokens, and Assets v;
Carousel Combat Tracker v;
Chat Commander v;
Chibbin Grove Free Compendium v;
Chris's Premades v;
Chronicler's Modified Rolls v;
Combat Booster: Turn Marker, Recent Actions and more v;
Combat Range Overlay v;
Compendium Folders v;
ConversationHUD v;
Coriolis AI art pack by kbender v;
Czepeku Sci-Fi - Arctic Institute v;
Czepeku Sci-Fi - Cyberpunk Streets v;
Czepeku Sci-Fi - Decimator Mech Depot v;
Czepeku Sci-Fi - Magnus Starship Part 1 v;
Damage Log v;
D&D5e Animations v;
D&D5e Character Monitor v;
DFreds Convenient Effects v;
Dice So Nice! v;
Dig Down - Advanced Search v;
DnD5e Drag Ruler Integration v;
DND5E Scriplets - 5E QOL bits and pieces v;
Drag Ruler v;
Dungeon Draw v;
Dynamic effects using Active Effects (DAE) v;
Easy Exports v;
Effect Macro v;
Filepicker Improvements v;
Find the culprit v;
Foundry Community Macros v;
Foundry Community Tables v;
GM Notes v;
GM Screen v;
Gridless Grid v;
Grid Scaler v;
Health Estimate v;
Hey, Wait! v;
Hyperdrive Fleet - Abyssal - Deep Sea Ship v;
Hyperdrive Fleet - Alien Mothership v;
Hyperdrive Fleet - Ancient World Forge v;
Hyperdrive Fleet - Aniamted Macrocheira - Repair Ship v;
Hyperdrive Fleet - Animated Abyssal - Deep Sea Ship v;
Hyperdrive Fleet - Animated Acorn Explorer v;
Hyperdrive Fleet - Animated Albatross - Long Range Explorer v;
Hyperdrive Fleet - Animated Ancient World Forge v;
Hyperdrive Fleet - Animated Asteria - Luxury Space Yacht v;
Hyperdrive Fleet - Animated Blue Swallow - Recon Vessel v;
Hyperdrive Fleet - Animated Cargo Camel v;
Hyperdrive Fleet - Animated Cassowary Shield Guardian v;
Hyperdrive Fleet - Animated Claymore Carrier v;
Hyperdrive Fleet - Animated Crystal Mines v;
Hyperdrive Fleet - Animated Dragonette Star Racer v;
Hyperdrive Fleet - Animated Dynamo Bomber v;
Hyperdrive Fleet - Animated Enlightener - Hell Frigate v;
Hyperdrive Fleet - Animated Extraction Point v;
Hyperdrive Fleet - Animated Exuvidax - Alien Cannon v;
Hyperdrive Fleet - Animated Hoopoe - Cargo Ship v;
Hyperdrive Fleet - Animated Husk Gnome Scythe v;
Hyperdrive Fleet - Animated Megaimperax - Alien Carrier v;
Hyperdrive Fleet - Animated Odyssey 12 - Terraformer v;
Hyperdrive Fleet - Animated Orbital Defence Cannon v;
Hyperdrive Fleet - Animated Ouroboros Part 2 v;
Hyperdrive Fleet - Animated Planatus - Bio-dome Research Vessel v;
Hyperdrive Fleet - Animated Prime Mover v;
Hyperdrive Fleet - Animated Razorbill - Interceptor v;
Hyperdrive Fleet - Animated Reactor Core v;
Hyperdrive Fleet - Animated Squengi's Grill v;
Hyperdrive Fleet - Animated - Urraca - Merchant Ship v;
Hyperdrive Fleet - Animated Zone 51 v;
Hyperdrive Fleet - Anura - Walker v;
Hyperdrive Fleet - Apocalyptic Fuel Station v;
Hyperdrive Fleet - Asteria - Luxury Space Yacht v;
Hyperdrive Fleet - Barracuda - Destroyer v;
Hyperdrive Fleet - Caladrius - Medical Ship v;
Hyperdrive Fleet - Canadensis - Blockade Runner v;
Hyperdrive Fleet - Cassowary v;
Hyperdrive Fleet - Crystal Mines v;
Hyperdrive Fleet - Cyberpunk Streets v;
Hyperdrive Fleet - Delphadox - Alien Navigator v;
Hyperdrive Fleet - Eversor v;
Hyperdrive Fleet - Hawkeye - Bounty Hunter v;
Hyperdrive Fleet - Hoopoe - Cargo Ship v;
Hyperdrive Fleet - Horus 918 - Far Portal v;
Hyperdrive Fleet - HWSS Empress v;
Hyperdrive Fleet - Leiothrix - Boarding Ship v;
Hyperdrive Fleet - Macrocheira - Repair Ship v;
Hyperdrive Fleet - Mavel III - Junk Bucket v;
Hyperdrive Fleet - Megaimperax - Alien Carrier v;
Hyperdrive Fleet - Odobenus - Prison Transport v;
Hyperdrive Fleet - Odyssey 12 - Terraformer v;
Hyperdrive Fleet - Orbital Defence Cannon v;
Hyperdrive Fleet - Ouroboros v;
Hyperdrive Fleet - Ouroboros v;
Hyperdrive Fleet - Ouroboros Part 2 v;
Hyperdrive Fleet - Ouroboros Part 3 v;
Hyperdrive Fleet - Prime Mover v;
Hyperdrive Fleet - Reactor Core v;
Hyperdrive Fleet - Sample Pack v;
Hyperdrive Fleet - Tettigarctidax - Fighter Ship v;
Hyperdrive Fleet - The Claymore Carrier v;
Hyperdrive Fleet - Zone 51 v;
Hyperlanes v;
Icon Picker v;
Illandril's Inventory Sorter (5e) v;
Image Previewer v;
Innocenti Open Lock v;
Item Macro v;
Item Piles v;
Items with Spells DnD5e v;
Jack Kerouac's Animated Spell Effects v;
Jack Kerouac's Animated Spell Effects: Cartoon v;
JB2A - Jules and Ben's Animated Assets - Free Content v;
Jinker's Animated Art Pack v;
Kanka-Foundry v;
Koboldworks – Data Inspector 🔍 v;
Lancer Weapon FX v;
Let Me Roll That For You! v;
Levels v;
lib - Color Settings v;
Lib: Document Sheet Registrar v;
Library - Find the Path v;
Library: Scene Packer v;
libWrapper v;
Limits v;
Loot Sheet NPC 5e (Simple Version) v;
Mass Edit v;
Math.js v;
Maxwell's Manual of Malicious Maladies v;
Melvin's Mechanical Masterworks v;
Midi QOL v;
Midi SRD v;
Miska's Maps - Battlemaps - Starter Pack v;
Monk's Active Tile Triggers v;
Monk's Bloodsplats v;
Monk's Chat Timer v;
Monk's Combat Details v;
Monk's Enhanced Journal v;
Monk's Enhanced Journal Objectives styles v;
Monk's Hotbar Expansion v;
Monk's Little Details v;
Monk's Scene Navigation v;
Monk's Shops v;
Monk's Sound Enhancements v;
Monk's TokenBar v;
Monk's Wall Enhancement v;
Moonlight Maps v;
Multiface Tiles v;
Multilevel Tokens v;
Note Licker v;
Not Your Turn! v;
Party Inventory v;
Party Resources v;
Patrol v;
Perceptive v;
Pin Cushion v;
Pings v;
Polyglot v;
Quick Insert - Search Widget v;
Rest Recovery for 5E v;
Rideable v;
Roll Groups v;
Roll Table from Sidebar and Journal v;
Sequencer v;
Settings Extender v;
Simbul's Athenaeum v;
Simbul's Cover Calculator v;
Simbul's Creature Aide v;
Simple Calendar v;
Skill Customization for D&D5e v;
SmallTime v;
Smart Target v;
socketlib v;
SoundFx Library v;
Speak As…… v;
Spellarena Battlemap Collection v;
Status Halo v;
Stealthy v;
Tabbed Chatlog v;
Tagger v;
Tasteful Tooltips v;
Template Macro v;
The Reclusive Cartographer | Free Foundry Content v;
TheRipper93's Module Hub v;
Tidy5e Sheet v;
Tidy UI - Game Settings v;
Times Up v;
Token Action HUD Core v;
Token Action HUD D&D 5e v;
Token Attacher v;
Tokenizer v;
Token Light Condition v;
Token Magic FX v;
Torch v;
User Latency v;
Variant Encumbrance+Midi v;
Vision 5e v;
Visual Active Effects v;
Walled Templates v;
Wall Height v;
Warp Gate v;
World Scripter v;
WTF: What the Flag? v;

Inactive Modules:
----------
Beaver's Potions v;
Concentration Notifier v;
Custom Character Sheet Sections v;
Darkraven Games Free Fantasy and Sci-Fi Soundscapes v;
Drag Upload (Get Over Here!) v;
Easy Target v;
Effective Transferral v;
Elevenlabs for Foundry v;
Enhanced Movement v;
Forien's Copy Environment v;
How unfortunate are you? Dice Counting v;
Mark Drummond J - Free Pack v;
Multiattack 5e v;
Plutonium v;
Plutonium Addon: Automation v;
Quick Grid Align v;
Ration Expiration Date v;
Smart Doors v;
Stat Drawer v;
Stellaris Compendium v;
Super's Homebrew Compendium v;
Sweet Nothings v;
Tabletop RPG Music v;
Tactical Grid v;

**Comment by Saibot393** [comment] 2023-09-28 15:46
To narrow it down, you were not using the spotting feature of the module, right?

**Comment by Saibot393** [comment] 2023-09-28 16:07
That would be quite helpfull, any error message including anything perceptive related would help me find this bug.

**Comment by weepingminotaur** [comment] 2023-09-28 17:27
> I am pretty sure those were my existing settings at the time, but I do not remember turning on the spot invisible feature. But I can report again with this module running to see what happens the next session

Honestly, with that many modules, you should check for console errors, and run Find the Culprit to see if there is a weird interaction going between Perceptive and another module. And maybe trim your active module list. For example, you're using both Let Me Roll That For you and Monk's TokenBar, which do more or less the same thing. Do you really need About Time if you're not running timed calendar events? And so on.

**Comment by Saibot393** [comment] 2023-10-05 15:41
Quick question here, what versions of Levels and Perceptive are you using?

**Comment by Angry-Maid** [comment] 2023-12-16 20:28
I don't know if this issue is related to his performance issues he has, but I do have constant spam messages which cause performance drops on latest(?, at least at the date of me writing on this issue and I do have a tad bit more modules but as far as I can tell after running find the culprit this combination causes those performance issues) versions of foundry, dfreds, stealthy, and perceptive.

- FoundryVTT v11.315
- System: D&D5e v2.4.1
- Perceptive v3.1.8
- Stealthy v3.13.2
- DFreds Convinient Effects v6.0.0
- DFreds Effects Panel v3.1.0
- Vision5e v1.11.0
- Arms React v2.3.6
- Dynamic effects using Active Effects (DAE) v11.1.7
- libWrapper v1.12.13.0 

And I'm constantly getting this warning that causes frequent performance drops whenever player characters moves around. Active Spot is disabled,
![image](https://github.com/Saibot393/perceptive/assets/24209146/964832c2-260f-4119-87ae-cda4ded108c8)
Here's settings that I have.(collapsible menu settings are set at default)
![image](https://github.com/Saibot393/perceptive/assets/24209146/1b713935-2199-4add-ad13-85a25d17052a)
![image](https://github.com/Saibot393/perceptive/assets/24209146/5ff57689-433f-4e37-8aff-ef8cbdb146de)

**Comment by Saibot393** [comment] 2023-12-16 21:10
This does not seem to be a (directly) perceptive related bug. To which ever module the `patches.js` file belongs does not seem to have correctly updated its code to v11

**Comment by Angry-Maid** [comment] 2023-12-16 21:18
Seems like Wall Height module. Okay.

**Comment by Saibot393** [comment] 2023-12-16 21:28
i will see if i can PR a solution for that

**Comment by Angry-Maid** [comment] 2023-12-16 21:31
Thanks, I did mention other modules because this chain of calls looks so wonky and I couldn't determine which one of them actually caused initial issue.

**Comment by Saibot393** [comment] 2023-12-16 21:35
yeah, it includes libwrapper which makes tracing the cause always a bit problematic by its very nature

**Comment by Saibot393** [comment] 2023-12-16 22:08
Should be fixed with Wall Height v5.1.4

**Comment by Saibot393** [comment] 2024-02-14 22:07
Is this still happening?

**Comment by Saibot393** [comment] 2024-03-25 14:44
So, is this still a problem for anyone?

**Comment by weepingminotaur** [comment] 2024-03-25 15:23
Not for me!

**Closed** 2024-03-27 18:13 UTC
Labels: bug

**Comment by XXDarrienX** [comment] 2024-04-16 20:13
Nope I have not had this issue recently at all

**Comment by Saibot393** [comment] 2024-04-16 20:15
Thank you for confirming
