### ISSUE TITLE
Console error and client freeze

### ISSUE THREAD

**Issue by ottyn** [Saibot393/perceptive#18] opened 2023-09-24 17:18 UTC
Foundry VTT v11.309
PF2e v5.5.3
Perceptive v1.9.5
Walled Templates v0.6.10

I receive the following error in the console when trying to place a template for the Seek action.  As soon as the template is placed on the canvas, the canvas completely freezes and the error shows up in the console.  I have tried this as both GM and Player with the same result.  Reloading the application allows the canvas to be used again but the template can't be moved or deleted.

![image](https://github.com/Saibot393/perceptive/assets/97130150/6a15c6d6-352b-42a7-b9e3-4f3788802744)

**Comment by ottyn** [comment] 2023-09-24 17:23
Definitely a conflict with Walled Templates.  Disabled Walled Templates and reloaded.  Tried the Seek action again and placed the template with no errors or issues.

**Comment by Saibot393** [comment] 2023-09-24 20:09
Thanks for reporting the bug. It should be fixed with v1.9.6.
I can however not replicate the bug, i will therefore leave the issue open until i get confirmation

**Comment by ottyn** [comment] 2023-09-24 20:33
@Saibot393 Just tested same scenario again after updating to v1.9.6.  No errors showing up in console and it allows me to place the template for Seek normally.  Thank you for such a quick response.

**Comment by Saibot393** [comment] 2023-09-24 20:44
Good to hear.
Since i am not 100% certain what caused the issue, there might be some odd behaviour or bugs caused by the fix. Should something like this happen feel free to open a new issue or append this one.

**Closed by Saibot393** 2023-09-24 20:44 UTC
Labels: bug
