### ISSUE TITLE
[Compatibility] Stealth features don't quite respect PF2e stealth rules

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/perceptive#14] opened 2023-09-23 02:03 UTC
A couple of places where the module doesn't really mesh with Pf2e:

- In Pf2e, you have multiple states of stealth depending on what you're doing. Hide confers Hidden, while Sneak confers Undetected. However, whenever I roll any kind of stealth check, Perceptive puts Undetected on the token regardless of whether it was a Hide or a Sneak check. If the module could differentiate between a Hide check and a Sneak check, it would be great.

- Right now, you can choose to have the stealth check set passive Perception DC for the token, active Perception for the token, or nothing. However, in Pf2e there is really no such thing as a contested roll. When you're trying to be stealthy, you roll a Stealth check against the other creature's Perception DC, which is the creature's Perception modifier + 10 (effectively passive Perception in 5e lingo). When the other creature is trying to find you, it rolls a Perception check against your Stealth DC, which is your Stealth mod + 10 (effectively passive Stealth). So the correct behaviour would be to have a creature's Active Perception DC to always and automatically be their Stealth DC (stealth mod + 10).

**Comment by Saibot393** [comment] 2023-09-23 07:42
I will look into it, should be relatively easy to implement. The biggest challange is probably the ui/controll and getting the frequency in which a a sneaking creature rolls the stealth check right.

**Comment by Saibot393** [comment] 2023-09-23 09:38
To save a bit of performance, do you think rerolling the stealth check every time a token moves and then comparing it against the perception dc of all tokens along the movement line would be close enough to the rules?

**Comment by Saibot393** [comment] 2023-09-23 17:42
I have implemented an option to use the Pf2e specific rules with v1.9.0. Since i am not sure if i have missed something i will leave this issue open for now.

**Comment by weepingminotaur** [comment] 2023-09-23 18:40
Awesome, thank you! Will test this out later and give feedback.

**Comment by weepingminotaur** [comment] 2023-09-25 02:27
Trying the latest version out and it's looking good! Pinging and chat notifications are working. With respect to Pf2e rules, there are still a couple of things that need to be aligned:

- Need to be able to define a token's Perception DC automatically (10 + Perception modifier) and have it always locked. This DC is used whenever a creature rolls a Stealth check against another creature. If a creature meets or exceeds the other creature's Perception DC, it becomes Hidden or Undetected from that creature. The thing is that the Perception DC is always a fixed value, with no dice roll. Ideally, it would be amazing if Perceptive simply used the Perception DC for every token dropped on the canvas.
- Active Stealth works fine, I think, since a creature has to make a Stealth check (Hide or Sneak) against the Perception DC of any creature that has it in view (Observed). For passive Stealth, though, it should be a fixed value for each creature (10 + Stealth modifier) and locked.
- The cone effect should probably be a macro, not a continuous effect, because a creature has to spend an action to Seek in combat. Would be great to have that macro bundled with Perceptive, along with the 15-foot burst version. (or a macro that let you pick between cone or burst and then laid the template down and checked for the result)

**Comment by weepingminotaur** [comment] 2023-09-25 03:50
Wait, I think Stealth is behaving OK. Tested with Shadow and its Active Perception DC is 24, which lines up perfectly with its Perception DC (10 + 14 Stealth).

**Comment by weepingminotaur** [comment] 2023-09-25 03:58
Spotting Distance for stealthed tokens doesn't seem to be working. Had it set to 10, with Lock-peeking at 5 and door-moving at 6, but the active token wasn't spotting an Undetected monster even within 10 feet. It only triggered when adjacent. So it seems to be taking lock-peeking or door-moving interaction distances instead.

**Comment by Saibot393** [comment] 2023-09-27 14:38
In addition to the improvements to the Pf2e stealth rules, a Border to border distance option for the vision range and a lock for the active dc have been implemented with v2.0.0. I will leave this issue open for in case i forgot something.

**Comment by weepingminotaur** [comment] 2023-09-27 23:19
Just a note: is it intended that the Perception macros don't work unless you have "only use Perceptive macros" checked? I would definitely want to be able to use the macros in combat for players actively Seeking but keep the ability to automate passive and active detection out of combat.

**Comment by Saibot393** [comment] 2023-09-28 04:16
Currently yes. The problem ist, that is did not find a way to differentiate between macro rolled and normally rolled checks, meaning that the checks rolled with the macros would be evaluated twice by the module. I can add option though, that the macros are only active during combat though.

**Comment by weepingminotaur** [comment] 2023-09-28 04:53
Yes, macros only active during combat would be perfect.

**Comment by Saibot393** [comment] 2023-09-28 13:35
I have added an option to only use the macros during combat with v2.0.3

**Comment by Saibot393** [comment] 2023-10-20 08:26
I think everything discussed in this issue should be implemented now, or did i miss something? If not i would close this issue.

**Closed** 2023-11-04 15:15 UTC
Labels: bug, enhancement
