### ISSUE TITLE
Active perception range not applied

### ISSUE THREAD

**Issue by Spuznik** [Saibot393/perceptive#35] opened 2023-10-29 11:22 UTC
When setting up a secret door for example, the active perception roll is not limited and doesn't use the spotting range when apply ranges : always  is enabled.

![msedge_dtDWw0FpTC](https://github.com/Saibot393/perceptive/assets/142272986/6b3e05e0-e6c6-4ea2-8404-2c60725bbd58)

**Comment by Saibot393** [comment] 2023-10-29 11:30
Could you send me a screenshot of your spotting range world settings?

**Comment by Spuznik** [comment] 2023-10-29 12:11
![image](https://github.com/Saibot393/perceptive/assets/142272986/27c2163c-5f8f-4d3a-9dbe-b5b0bcf379f1)

Tried several options and the always condition only seems to be a problem. Passive or Active work as long as you make the other condition impossible (-1) on the wall.

**Comment by Saibot393** [comment] 2023-10-29 12:23
I asume you are testing as a GM, are you using the setting Player perspective?

**Comment by Spuznik** [comment] 2023-10-29 12:58
Yes I have tested as both, not many options as a player just the ping. I also noted that I also noted in testing if you have the Passive as Impossible, but Active has a value the Passive spot is triggering. The door symbol isnt displayed, but the ping is.

![image](https://github.com/Saibot393/perceptive/assets/142272986/8f10dd0e-9672-4795-aee7-a3441943c51d)

![image](https://github.com/Saibot393/perceptive/assets/142272986/91ed01fe-f19a-4012-a2b6-8e2192e2145b)

![msedge_EJM0CMpZcz](https://github.com/Saibot393/perceptive/assets/142272986/ca1d9a3a-e192-45d6-8021-3237937a879e)

**Comment by Saibot393** [comment] 2023-10-29 13:10
Could there be a lingering active perception on the token?

**Comment by Spuznik** [comment] 2023-10-29 13:18
It only puts a value in the spotted by spotting info on the actual active check. See below. 

![chrome_ivuVzzqnTL](https://github.com/Saibot393/perceptive/assets/142272986/8e96a89c-6a8a-4ea3-bd7b-e54d209ad79a)

**Comment by Spuznik** [comment] 2023-10-29 13:20
Heading off. If you need me to check some more tomorrow I can.

**Comment by Saibot393** [comment] 2023-10-29 14:06
I have added a debug mode with v2.6.3 (can be activated with `CONFIG.debug.perceptive.SpottingScript = true`), can you turn this on and send me the console output (starting with `perceptive:`), maybe this will help understanding what happens

**Comment by Saibot393** [comment] 2023-10-29 20:45
I think i have finally found the bug, it should be fixed with v2.6.4

**Comment by Spuznik** [comment] 2023-10-29 23:26
Tested again this morning. Created a new scene and placed a small building. Added a secret door to the back wall. Put the Passive value to 50 so no chance it can be met. Active set to 12. When player token moves around to see the back wall the ping goes off. See below. It looks like the DC isnt being checked, and as soon as the perceptive enabled wall is in sight it triggers.

![image](https://github.com/Saibot393/perceptive/assets/142272986/1d4b93cc-f7f7-49a0-871f-4a1d9718dc89)
![image](https://github.com/Saibot393/perceptive/assets/142272986/47615110-27ae-47a4-b4eb-2ae48c1c1ab3)

TestTile is set to just rotate on NewlySpotted trigger

 Player recording:

![msedge_MuZ87yll9B](https://github.com/Saibot393/perceptive/assets/142272986/7711503a-dbb0-4f7c-8f7a-afd91e4f4011)

**Comment by Spuznik** [comment] 2023-10-29 23:29
Happy to do a discord session tonight if you want. I am in Australia, so not sure of you location and time zone

**Comment by Saibot393** [comment] 2023-10-29 23:32
I am in germany so its quite late in the evening for me. The behaviour in the above video seems to be expected though, assuming that the token used is "Matilda Mistshadow" as this token seems to already have spotted the door according to the first screenshot

**Comment by Spuznik** [comment] 2023-10-30 00:39
The wall that is being pinged shouldnt be seen initially but it does with
the Passive either as -1 impossible or above the players Passive Perception
value. So I think there is still a bug on how it checks range and DC for
passive. Also can you reset the flags on who has seen the wall, tile,
token?

**Comment by Saibot393** [comment] 2023-10-30 07:11
A reset is of the spotted by is currently not directly possible, i will include a button for that in the next version

**Comment by Spuznik** [comment] 2023-10-30 09:21
I think I have found what is happening and currently seems to be correct. Once the token has seen the tile, token or wall once through either passive or active DC check that object is no longer usable for testing as the "flag" or whatever you are using for tracking causes the ping to fire. Which is the behaviour of what you mentioned is expected. I have been creating some of the perceptive targets in the vicinity of the player token, so its triggered before I know it.  I think the reset will fix the issues for testing.

**Comment by Spuznik** [comment] 2023-10-30 09:26
Also any chance that the perceptive range can be added to the tile, token or wall as an option in the perceptive tab, this way you can have more granular control on where the spot will work.

**Comment by Saibot393** [comment] 2023-10-30 09:28
You mean a range per object? That shouldn't be a problem but will take a bit of time, i will probably release the update with the reset spotted by button in the next few hours, but the range per object setting will probably take a few days.

**Comment by Saibot393** [comment] 2023-10-30 09:51
I have just released v2.6.6 which adds a button to the object settings which allows for the reset of the "spotted by" list, notice that the change will only apply visually once the effected tokens update their vision by e.g. moving

**Comment by Saibot393** [comment] 2023-11-01 10:20
Sorry, i lost overview over this issue. Are there still weird/unexpected behaviours?

**Comment by Spuznik** [comment] 2023-11-02 00:09
Let me check based on your new version 2.7.1 and I'll update

**Comment by Saibot393** [comment] 2023-11-04 15:15
> Also any chance that the perceptive range can be added to the tile, token or wall as an option in the perceptive tab, this way you can have more granular control on where the spot will work.

This can now be done with v2.8.0

**Comment by Saibot393** [comment] 2023-11-17 11:14
I am fairly certain, that the bug should be fixed. Unless i hear otherwise, i will close this issue soon.

**Closed** 2023-11-25 23:00 UTC
Labels: bug
